export const AUTH_ERROR_CODES = {
  PASSWORD_LOGIN_DISABLED: 'PASSWORD_LOGIN_DISABLED',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED'
} as const

export const BOARD_ERROR_CODES = {
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  BOARD_ARCHIVED: 'BOARD_ARCHIVED',
  BOARD_ACCESS_DENIED: 'BOARD_ACCESS_DENIED'
} as const
